services:
  - type: web
    name: tamil-stream-app
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run serve:ssr:app
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
